### Import necessary library
This cell imports the `one_hot` function from `tensorflow.keras.preprocessing.text` for text tokenization.

In [32]:
from tensorflow.keras.preprocessing.text import one_hot

### Define sample sentences
This cell defines a list of sample sentences that will be used for demonstration.

In [33]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

### Display sentences
This cell displays the list of sample sentences.

In [34]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

### Define vocabulary size
This cell sets the size of the vocabulary for one-hot encoding.

In [35]:
## Define the vocabulary size
voc_size=10000

### One-Hot Representation
This cell applies one-hot encoding to each sentence using the defined vocabulary size.

In [36]:
### One Hot Representation
one_hot_repr = [ one_hot(words,voc_size)for words in sent ]
one_hot_repr

[[1550, 1497, 2996, 885],
 [1550, 1497, 2996, 2824],
 [1550, 6966, 2996, 1121],
 [61, 4541, 5236, 119, 9764],
 [61, 4541, 5236, 119, 1648],
 [6862, 1550, 2850, 2996, 1348],
 [8032, 8488, 9103, 119]]

### Import libraries for Word Embedding
This cell imports necessary layers and models from TensorFlow/Keras for creating a word embedding model, as well as `pad_sequences` for sequence padding.

In [37]:
## word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

### Import NumPy
This cell imports the NumPy library, which is commonly used for numerical operations in Python.

In [38]:
import numpy as np

### Pad sequences
This cell pads the one-hot encoded sequences to a fixed length (`sent_length`) using pre-padding.

In [39]:
sent_length = 8
embedded_doc = pad_sequences(one_hot_repr,padding='pre',maxlen = sent_length)
print(embedded_doc)

[[   0    0    0    0 1550 1497 2996  885]
 [   0    0    0    0 1550 1497 2996 2824]
 [   0    0    0    0 1550 6966 2996 1121]
 [   0    0    0   61 4541 5236  119 9764]
 [   0    0    0   61 4541 5236  119 1648]
 [   0    0    0 6862 1550 2850 2996 1348]
 [   0    0    0    0 8032 8488 9103  119]]


### Define embedding dimension
This cell defines the dimension of the word embeddings.

In [40]:
## feature representation
dim=10

### Create and compile embedding model
This cell creates a simple Sequential model with an Embedding layer. The model is compiled with the Adam optimizer and mean squared error loss.

In [41]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


### Display model summary
This cell displays a summary of the created model, showing the layers and parameters.

In [42]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

### Predict embeddings for all sentences
This cell uses the trained embedding model to predict the embeddings for all the padded sequences.

In [43]:
model.predict(embedded_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 204ms/step


array([[[-0.00467901, -0.00231373, -0.02180827,  0.01534377,
          0.03669937,  0.04962161,  0.03154228,  0.02740307,
         -0.03027835,  0.00232493],
        [-0.00467901, -0.00231373, -0.02180827,  0.01534377,
          0.03669937,  0.04962161,  0.03154228,  0.02740307,
         -0.03027835,  0.00232493],
        [-0.00467901, -0.00231373, -0.02180827,  0.01534377,
          0.03669937,  0.04962161,  0.03154228,  0.02740307,
         -0.03027835,  0.00232493],
        [-0.00467901, -0.00231373, -0.02180827,  0.01534377,
          0.03669937,  0.04962161,  0.03154228,  0.02740307,
         -0.03027835,  0.00232493],
        [ 0.02327278,  0.01306433, -0.00878923,  0.02516599,
         -0.00067272, -0.02039397, -0.00201815,  0.03409041,
         -0.02012038, -0.00958437],
        [ 0.02557745,  0.02042638, -0.00111772,  0.010258  ,
         -0.0157359 , -0.0293309 ,  0.00081437,  0.0274283 ,
         -0.04709252,  0.01201929],
        [ 0.01957877, -0.03016071, -0.03244666, -0.0

### Display the first embedded document
This cell displays the first padded and embedded sequence.

In [44]:
embedded_doc[0]

array([   0,    0,    0,    0, 1550, 1497, 2996,  885], dtype=int32)

### Predict embedding for a single sentence
This cell predicts the embedding for the first sentence, ensuring the input has the correct batch dimension.

In [45]:
model.predict(np.expand_dims(embedded_doc[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step


array([[[-0.00467901, -0.00231373, -0.02180827,  0.01534377,
          0.03669937,  0.04962161,  0.03154228,  0.02740307,
         -0.03027835,  0.00232493],
        [-0.00467901, -0.00231373, -0.02180827,  0.01534377,
          0.03669937,  0.04962161,  0.03154228,  0.02740307,
         -0.03027835,  0.00232493],
        [-0.00467901, -0.00231373, -0.02180827,  0.01534377,
          0.03669937,  0.04962161,  0.03154228,  0.02740307,
         -0.03027835,  0.00232493],
        [-0.00467901, -0.00231373, -0.02180827,  0.01534377,
          0.03669937,  0.04962161,  0.03154228,  0.02740307,
         -0.03027835,  0.00232493],
        [ 0.02327278,  0.01306433, -0.00878923,  0.02516599,
         -0.00067272, -0.02039397, -0.00201815,  0.03409041,
         -0.02012038, -0.00958437],
        [ 0.02557745,  0.02042638, -0.00111772,  0.010258  ,
         -0.0157359 , -0.0293309 ,  0.00081437,  0.0274283 ,
         -0.04709252,  0.01201929],
        [ 0.01957877, -0.03016071, -0.03244666, -0.0